// Lint and index the keyed-block reference docs (`## [@ns:ID] Title` ... `END_DOC_BLOCK: [@ns:ID]`).
// CLI: node scripts/docsKeys.mjs lint | index [--check]
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

export const MAX_BLOCK_BYTES = 6200;
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS_DIR = join(ROOT, 'docs');
const INDEX_PATH = join(ROOT, 'docs/INDEX.md');
const INDEX_REL = 'docs/INDEX.md';
const SKIP_DIRS = new Set(['plans', 'superpowers']);
const SKIP_FILES = new Set(['docs/extension-inventory.md', 'docs/arch/extension-inventory.md', INDEX_REL]);
const OPEN = /^## \[@([^\]]+)\] (.*)$/;
const END = /^END_DOC_BLOCK: \[@([^\]]+)\]\s*$/;
const FENCE = /^\s{0,3}(`{3,}|~{3,})/;
const HEADER = /^<!-- AGENT INSTRUCTIONS:[\s\S]*?-->/;

function parse(text) {
  const header = HEADER.exec(text)?.[0] ?? null;
  const body = header ? text.slice(header.length) : text;
  const blocks = [];
  const errors = [];
  let fence = null;
  let cur = null;
  for (const line of body.split(/\r?\n/)) {
    const size = Buffer.byteLength(line) + 1;
    const f = FENCE.exec(line)?.[1];
    if (f && !fence) fence = f;
    else if (f && f[0] === fence[0] && f.length >= fence.length && line.trim() === f) fence = null;
    if (fence || f) {
      if (cur) cur.bytes += size;
      continue;
    }
    const open = OPEN.exec(line);
    const end = END.exec(line);
    if (open) {
      if (cur) errors.push(`${cur.id}: no END before next block`);
      cur = { id: open[1], title: open[2], bytes: size };
    } else if (end) {
      if (!cur) errors.push(`${end[1]}: END without open block`);
      else if (cur.id !== end[1]) errors.push(`${cur.id}: END mismatch (found ${end[1]})`);
      if (cur) blocks.push({ ...cur, bytes: cur.bytes + size });
      cur = null;
    } else {
      if (line.startsWith('## ')) errors.push(`unkeyed ## heading: ${line.slice(0, 60)}`);
      if (cur) cur.bytes += size;
    }
  }
  if (cur) errors.push(`${cur.id}: no END marker`);
  return { header, blocks, errors };
}

export function lintDoc({ path, text }) {
  const { header, blocks, errors } = parse(text);
  const out = errors.map((e) => `${path}: ${e}`);
  if (!header) return [`${path}: missing AGENT INSTRUCTIONS header`, ...out];
  if (header.includes('<file_path>')) out.push(`${path}: header has <file_path> placeholder`);
  const cmdLines = header.split(/\r?\n/).filter((l) => /^\s+(grep|awk)\b/.test(l));
  for (const p of new Set(cmdLines.flatMap((l) => l.match(/[\w./-]+\.md\b/g) ?? []))) {
    if (p !== path) out.push(`${path}: header path ${p} does not match this file`);
  }
  const seen = new Set();
  for (const b of blocks) {
    if (seen.has(b.id)) out.push(`${path}: duplicate id ${b.id}`);
    seen.add(b.id);
    if (b.bytes > MAX_BLOCK_BYTES) out.push(`${path}: ${b.id} exceeds ${MAX_BLOCK_BYTES} B (${b.bytes})`);
  }
  return out;
}

export function buildIndex(docs) {
  const lines = [];
  for (const d of [...docs].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))) {
    for (const b of parse(d.text).blocks) lines.push(`[@${b.id}] ${d.path} — ${b.title}`);
  }
  return [
    '# Docs key index (generated)',
    '',
    'Generated by `npm run -s docs:index`. Do not edit. Search it, never read it whole:',
    '`grep -i <topic> docs/INDEX.md`, then extract the block with the awk recipe in the file header.',
    '',
    ...lines,
    '',
  ].join('\n');
}

function collect(dir = DOCS_DIR) {
  const files = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) {
      if (!SKIP_DIRS.has(e.name)) files.push(...collect(p));
    } else if (e.name.endsWith('.md')) {
      const rel = relative(ROOT, p).split(sep).join('/');
      if (!SKIP_FILES.has(rel)) files.push({ path: rel, text: readFileSync(p, 'utf8') });
    }
  }
  return files;
}

function main(cmd, flags) {
  const docs = collect();
  if (cmd === 'lint') {
    const errs = docs.flatMap(lintDoc);
    if (errs.length) console.error(errs.join('\n'));
    process.exitCode = errs.length ? 1 : 0;
  } else if (cmd === 'index') {
    const next = buildIndex(docs);
    if (flags.includes('--check')) {
      let cur = '';
      try { cur = readFileSync(INDEX_PATH, 'utf8'); } catch { /* missing counts as stale */ }
      if (cur !== next) { console.error(`${INDEX_REL} is stale: run npm run -s docs:index`); process.exitCode = 1; }
    } else writeFileSync(INDEX_PATH, next);
  } else {
    console.error('usage: docsKeys.mjs lint | index [--check]');
    process.exitCode = 2;
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main(process.argv[2], process.argv.slice(3));
